/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    1: typeof import('./src/components/1.vue')['default']
    2: typeof import('./src/components/2.vue')['default']
    3: typeof import('./src/components/3.vue')['default']
    4: typeof import('./src/components/4.vue')['default']
    5: typeof import('./src/components/5.vue')['default']
    6: typeof import('./src/components/6.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppList: typeof import('./src/components/AppList.vue')['default']
    AppMain: typeof import('./src/components/AppMain.vue')['default']
    AppNavigation: typeof import('./src/components/AppNavigation.vue')['default']
    AppPlaceholder: typeof import('./src/components/AppPlaceholder.vue')['default']
    DeleteConfirmDialog: typeof import('./src/components/DeleteConfirmDialog.vue')['default']
    EditorDialog: typeof import('./src/components/EditorDialog.vue')['default']
    MainFilter: typeof import('./src/components/MainFilter.vue')['default']
    MainItemList: typeof import('./src/components/MainItemList.vue')['default']
    MainPlaceholderList: typeof import('./src/components/MainPlaceholderList.vue')['default']
    NavigationList: typeof import('./src/components/NavigationList.vue')['default']
    NaviListSection: typeof import('./src/components/Navi-ListSection.vue')['default']
    OmikujiEditor: typeof import('./src/components/OmikujiEditor.vue')['default']
    OmikujiEditorFiltering: typeof import('./src/components/OmikujiEditorFiltering.vue')['default']
    OmikujiEditorMessage: typeof import('./src/components/OmikujiEditorMessage.vue')['default']
    OmikujiList: typeof import('./src/components/OmikujiList.vue')['default']
    PlaceEditor: typeof import('./src/components/PlaceEditor.vue')['default']
    RandomEditor: typeof import('./src/components/RandomEditor.vue')['default']
    RuleEditor: typeof import('./src/components/RuleEditor.vue')['default']
    'コピー': typeof import('./src/components/NavigationList - コピー.vue')['default']
  }
}
