/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DeleteConfirmDialog: typeof import('./src/components/DeleteConfirmDialog.vue')['default']
    NavigationList: typeof import('./src/components/NavigationList.vue')['default']
    NaviListSection: typeof import('./src/components/Navi-ListSection.vue')['default']
    OmikujiEditor: typeof import('./src/components/OmikujiEditor.vue')['default']
    RandomEditor: typeof import('./src/components/RandomEditor.vue')['default']
    RuleEditor: typeof import('./src/components/RuleEditor.vue')['default']
    'コピー': typeof import('./src/components/NavigationList - コピー.vue')['default']
  }
}
